BEGIN;

CREATE SCHEMA IF NOT EXISTS online_retail;

CREATE TABLE IF NOT EXISTS online_retail.log_execucao (
    batch_id                 VARCHAR(64) PRIMARY KEY,
    inicio_execucao          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fim_execucao             TIMESTAMPTZ,
    status                   VARCHAR(16) NOT NULL DEFAULT 'RUNNING',
    arquivo_origem           TEXT,
    linhas_origem            BIGINT NOT NULL DEFAULT 0,
    linhas_staging           BIGINT NOT NULL DEFAULT 0,
    linhas_validas           BIGINT NOT NULL DEFAULT 0,
    linhas_rejeitadas        BIGINT NOT NULL DEFAULT 0,
    duplicatas_removidas     BIGINT NOT NULL DEFAULT 0,
    linhas_fato              BIGINT NOT NULL DEFAULT 0,
    mensagem_erro            TEXT,
    CONSTRAINT ck_log_execucao_status
      CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED')),
    CONSTRAINT ck_log_execucao_fim
      CHECK (fim_execucao IS NULL OR fim_execucao >= inicio_execucao)
);

CREATE TABLE IF NOT EXISTS online_retail.stg_online_retail (
    batch_id                 VARCHAR(64) NOT NULL,
    linha_seq                BIGINT NOT NULL,
    invoice_no               TEXT,
    stock_code               TEXT,
    description              TEXT,
    quantity_original        TEXT,
    invoice_date_original    TEXT,
    unit_price_original      TEXT,
    customer_id_original     TEXT,
    country_original         TEXT,
    registro_hash            CHAR(64),
    data_carga               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_stg_online_retail PRIMARY KEY (batch_id, linha_seq),
    CONSTRAINT ck_stg_linha_seq CHECK (linha_seq > 0)
);

CREATE TABLE IF NOT EXISTS online_retail.rejeitados (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id                 VARCHAR(64) NOT NULL,
    linha_seq                BIGINT NOT NULL,
    invoice_no               TEXT,
    stock_code               TEXT,
    description              TEXT,
    quantity_original        TEXT,
    invoice_date_original    TEXT,
    unit_price_original      TEXT,
    customer_id_original     TEXT,
    country_original         TEXT,
    motivo                   VARCHAR(100) NOT NULL,
    detalhe                  TEXT,
    data_rejeicao            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_rejeitados_execucao
      UNIQUE (batch_id, linha_seq, motivo),
    CONSTRAINT ck_rejeitados_linha_seq CHECK (linha_seq > 0)
);

CREATE TABLE IF NOT EXISTS online_retail.wrk_online_retail_validos (
    batch_id                 VARCHAR(64) NOT NULL,
    linha_seq                BIGINT NOT NULL,
    invoice_no               VARCHAR(20) NOT NULL,
    stock_code               VARCHAR(50) NOT NULL,
    description              TEXT,
    quantity                 INTEGER NOT NULL,
    invoice_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    unit_price               NUMERIC(18,4) NOT NULL,
    customer_id              BIGINT,
    country                  VARCHAR(100) NOT NULL,
    cancelamento             BOOLEAN NOT NULL,
    valor_total              NUMERIC(20,4) NOT NULL,
    registro_hash            CHAR(64),
    data_tratamento          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_wrk_online_retail_validos
      PRIMARY KEY (invoice_no, stock_code, linha_seq),
    CONSTRAINT ck_wrk_linha_seq CHECK (linha_seq > 0),
    CONSTRAINT ck_wrk_preco_positivo CHECK (unit_price > 0),
    CONSTRAINT ck_wrk_quantidade
      CHECK (cancelamento OR quantity > 0)
);

CREATE TABLE IF NOT EXISTS online_retail.dim_produto (
    produto_sk               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_code               VARCHAR(50) NOT NULL,
    description              TEXT,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_produto_stock_code UNIQUE (stock_code)
);

CREATE TABLE IF NOT EXISTS online_retail.dim_pais (
    pais_sk                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country                  VARCHAR(100) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_pais_country UNIQUE (country)
);

CREATE TABLE IF NOT EXISTS online_retail.dim_tempo (
    tempo_sk                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data                     DATE NOT NULL,
    dia                      SMALLINT NOT NULL,
    mes                      SMALLINT NOT NULL,
    nome_mes                 VARCHAR(20) NOT NULL,
    trimestre                SMALLINT NOT NULL,
    ano                      SMALLINT NOT NULL,
    dia_semana               VARCHAR(20) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_dim_tempo_data UNIQUE (data),
    CONSTRAINT ck_dim_tempo_dia CHECK (dia BETWEEN 1 AND 31),
    CONSTRAINT ck_dim_tempo_mes CHECK (mes BETWEEN 1 AND 12),
    CONSTRAINT ck_dim_tempo_trimestre CHECK (trimestre BETWEEN 1 AND 4)
);

CREATE TABLE IF NOT EXISTS online_retail.fato_venda (
    venda_sk                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_no               VARCHAR(20) NOT NULL,
    stock_code               VARCHAR(50) NOT NULL,
    linha_seq                BIGINT NOT NULL,
    produto_sk               BIGINT NOT NULL,
    pais_sk                  BIGINT NOT NULL,
    tempo_sk                 BIGINT NOT NULL,
    customer_id              BIGINT,
    quantity                 INTEGER NOT NULL,
    unit_price               NUMERIC(18,4) NOT NULL,
    valor_total              NUMERIC(20,4) NOT NULL,
    cancelamento             BOOLEAN NOT NULL,
    invoice_date             TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    batch_id                 VARCHAR(64) NOT NULL,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_fato_venda_chave_natural
      UNIQUE (invoice_no, stock_code, linha_seq),
    CONSTRAINT fk_fato_venda_produto
      FOREIGN KEY (produto_sk) REFERENCES online_retail.dim_produto (produto_sk),
    CONSTRAINT fk_fato_venda_pais
      FOREIGN KEY (pais_sk) REFERENCES online_retail.dim_pais (pais_sk),
    CONSTRAINT fk_fato_venda_tempo
      FOREIGN KEY (tempo_sk) REFERENCES online_retail.dim_tempo (tempo_sk),
    CONSTRAINT ck_fato_linha_seq CHECK (linha_seq > 0),
    CONSTRAINT ck_fato_preco_positivo CHECK (unit_price > 0),
    CONSTRAINT ck_fato_quantidade
      CHECK (cancelamento OR quantity > 0)
);

CREATE TABLE IF NOT EXISTS online_retail.indicadores_resumo (
    batch_id                 VARCHAR(64) PRIMARY KEY,
    calculado_em             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    faturamento_bruto        NUMERIC(20,4) NOT NULL DEFAULT 0,
    valor_cancelado          NUMERIC(20,4) NOT NULL DEFAULT 0,
    faturamento_liquido      NUMERIC(20,4) NOT NULL DEFAULT 0,
    quantidade_vendida       BIGINT NOT NULL DEFAULT 0,
    quantidade_cancelada     BIGINT NOT NULL DEFAULT 0,
    invoices_venda           BIGINT NOT NULL DEFAULT 0,
    invoices_canceladas      BIGINT NOT NULL DEFAULT 0,
    ticket_medio             NUMERIC(20,4) NOT NULL DEFAULT 0,
    taxa_cancelamento_pct    NUMERIC(9,4) NOT NULL DEFAULT 0,
    total_linhas_fato        BIGINT NOT NULL DEFAULT 0,
    customer_id_nulos        BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_indicadores_resumo_execucao
      FOREIGN KEY (batch_id) REFERENCES online_retail.log_execucao (batch_id)
);

CREATE INDEX IF NOT EXISTS ix_stg_online_retail_batch
  ON online_retail.stg_online_retail (batch_id);
CREATE INDEX IF NOT EXISTS ix_stg_online_retail_hash
  ON online_retail.stg_online_retail (registro_hash);
CREATE INDEX IF NOT EXISTS ix_rejeitados_batch_motivo
  ON online_retail.rejeitados (batch_id, motivo);
CREATE INDEX IF NOT EXISTS ix_wrk_online_retail_batch
  ON online_retail.wrk_online_retail_validos (batch_id);
CREATE INDEX IF NOT EXISTS ix_wrk_online_retail_produto
  ON online_retail.wrk_online_retail_validos (stock_code);
CREATE INDEX IF NOT EXISTS ix_wrk_online_retail_pais
  ON online_retail.wrk_online_retail_validos (country);
CREATE INDEX IF NOT EXISTS ix_wrk_online_retail_data
  ON online_retail.wrk_online_retail_validos (invoice_date);
CREATE INDEX IF NOT EXISTS ix_fato_venda_produto
  ON online_retail.fato_venda (produto_sk);
CREATE INDEX IF NOT EXISTS ix_fato_venda_pais
  ON online_retail.fato_venda (pais_sk);
CREATE INDEX IF NOT EXISTS ix_fato_venda_tempo
  ON online_retail.fato_venda (tempo_sk);
CREATE INDEX IF NOT EXISTS ix_fato_venda_batch
  ON online_retail.fato_venda (batch_id);
CREATE INDEX IF NOT EXISTS ix_fato_venda_invoice
  ON online_retail.fato_venda (invoice_no);

CREATE OR REPLACE FUNCTION online_retail.fn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_dim_produto_updated_at
  ON online_retail.dim_produto;
CREATE TRIGGER trg_dim_produto_updated_at
BEFORE UPDATE ON online_retail.dim_produto
FOR EACH ROW EXECUTE FUNCTION online_retail.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_dim_pais_updated_at
  ON online_retail.dim_pais;
CREATE TRIGGER trg_dim_pais_updated_at
BEFORE UPDATE ON online_retail.dim_pais
FOR EACH ROW EXECUTE FUNCTION online_retail.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_dim_tempo_updated_at
  ON online_retail.dim_tempo;
CREATE TRIGGER trg_dim_tempo_updated_at
BEFORE UPDATE ON online_retail.dim_tempo
FOR EACH ROW EXECUTE FUNCTION online_retail.fn_set_updated_at();

DROP TRIGGER IF EXISTS trg_fato_venda_updated_at
  ON online_retail.fato_venda;
CREATE TRIGGER trg_fato_venda_updated_at
BEFORE UPDATE ON online_retail.fato_venda
FOR EACH ROW EXECUTE FUNCTION online_retail.fn_set_updated_at();

COMMENT ON TABLE online_retail.stg_online_retail IS
  'Cópia textual da fonte; nenhuma conversão destrutiva ocorre nesta camada.';
COMMENT ON TABLE online_retail.rejeitados IS
  'Linhas descartadas, incluindo duplicatas integrais. As colunas *_original preservam o conteúdo exato recebido da fonte, coluna a coluna, e linha_seq aponta a linha da planilha.';
COMMENT ON TABLE online_retail.wrk_online_retail_validos IS
  'Linhas tipadas e aprovadas pela qualidade, prontas para a carga dimensional.';
COMMENT ON TABLE online_retail.fato_venda IS
  'Vendas e cancelamentos; valor_total é assinado e cancelamentos preservam valor negativo.';
COMMENT ON CONSTRAINT uq_fato_venda_chave_natural
  ON online_retail.fato_venda IS
  'Garante idempotência pela posição determinística da linha na fonte.';

COMMIT;
